name: deploy-site-prod
on: 
  push: 
    branches:
      - main
jobs:
  build:
    name: Checkout main branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch of lasyam_website repository
        uses: actions/checkout@v3
        with:
          ref: main
  deploy:
    name: Setup commands for SSH command
    runs-on: ubuntu-latest
    steps:
      - name: Initialize SSH configuration
        run: |
              touch ~/.ssh/host
              touch ~/.ssh/host.pub
              cat ${{secrets.SSH_HOST}} > ~/.ssh/host.pub
              cat ${{secrets.SSH_KEY}} > ~/.ssh/host
      - name: SSH into web server
        run: |
              ssh-add host
              ssh -l ${{secrets.SSH_USERNAME}} ${{secrets.SSH_DOMAIN}}}
      - name: Pull updated files from main branch of remote repository
        run: |
              cd ~/public_html/
              git pull origin main
              echo "Update to web server files successful."
